Hotel/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home_module.urls',namespace='home')),
    path('register/', include('account_module.urls', namespace='register')),
    path('panel/', include('user_panel_module.urls',namespace='panel')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

account_module/urls.py
from django.urls import path
from . import views


app_name = 'register'
urlpatterns = [
    path('', views.RegisterView.as_view(), name='register_page'),
    path('login/', views.UserLoginView.as_view(), name='login_page'),
    path('about/', views.StaffView.as_view(), name='about'),
    path('logout/', views.LogoutView.as_view(), name='logout_page'),

]

account_module/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


# Create your models here.

class User(AbstractUser):
    National_Id = models.CharField(max_length=10, verbose_name='کد ملی')
    phone_number = models.CharField(max_length=13, verbose_name='شماره تلفن')
    State = models.CharField(max_length=50, verbose_name='استان', null=True)
    city = models.CharField(max_length=50, verbose_name='شهر', null=True)

    def __str__(self):
        if self.first_name is not '' and self.last_name is not '':
            return self.get_full_name()
        return self.National_Id

    class Meta:
        verbose_name = 'کاربر'
        verbose_name_plural = 'کاربران'


class Staff(models.Model):
    name = models.CharField(max_length=200, verbose_name='نام')
    family = models.CharField(max_length=200, verbose_name='نام خانوادگی')
    role = models.CharField(max_length=200, verbose_name='سمت')
    phone = models.CharField(max_length=200, verbose_name='شماره همراه', null=True, blank=True)

    def __str__(self):
        return self.role

    class Meta:
        verbose_name = 'کارکنان'
        verbose_name_plural = 'کارکنان'

account_module/forms.py
from django import forms
from django.core.exceptions import ValidationError


class RegisterForm(forms.Form):
    National_Id = forms.CharField(
        max_length=10,
        label='کد ملی'
    )
    password = forms.CharField(
        widget=forms.PasswordInput(),
        label='پسورد'
    )
    confirm_password = forms.CharField(
        widget=forms.PasswordInput(),
        label='تکرار پسورد'

    )

    def clean_confirm_password(self):
        password = self.cleaned_data.get('password')
        confirm_password = self.cleaned_data.get('confirm_password')
        if password == confirm_password:
            return confirm_password
        return ValidationError('کلمه عبور با تکرار آن مغایرت دارد')


class LoginForm(forms.Form):
    National_Id = forms.CharField(
        max_length=10,
        label='کد ملی'
    )
    password = forms.CharField(
        widget=forms.PasswordInput(),
        label='پسورد'
    )

account_module/views.py
from django.contrib.auth import login, logout
from django.contrib.auth.views import LoginView
from django.shortcuts import render, redirect
from django.urls import reverse, reverse_lazy
from django.views import View
from django.views.generic import ListView, CreateView
from account_module.forms import RegisterForm, LoginForm
from account_module.models import User, Staff


class RegisterView(CreateView):
    template_name = 'account_module/register_page.html'
    model = User
    fields = ['National_Id', 'password']
    success_url = reverse_lazy('register:login_page')

    def form_valid(self, form):
        if User.objects.filter(National_Id=form.cleaned_data['National_Id']).exists():
            form.add_error('National_Id', 'کاربر قبلا در سایت ثبت نام کرده است')

        else:
            user = User.objects.create_user(username=form.cleaned_data['National_Id'])
            user.is_active = True
            user.set_password(form.cleaned_data['password'])
            user.save()
        return super().form_valid(form)


class UserLoginView(LoginView):
    template_name = 'account_module/login.html'
    next_page = reverse_lazy('home:room')


class StaffView(ListView):
    template_name = 'account_module/about.html'
    model = Staff


class LogoutView(View):
    def get(self, request):
        logout(request)
        return redirect(reverse('home:room'))

account_module/templates/account_module/about.html
{% extends 'base.html' %}
{% block body %}
<div class="col-sm-12 about-address">
    <address>
        {% for stafs in object_list %}

            <p>
                سمت : {{ stafs.role }} |
                <br>
                {% if stafs.phone %}
                    تلفن تماس : {{ stafs.phone }} |

                {% endif %}
                نام و نام خانوادگی: {{ stafs.name }} {{ stafs.family }}
            </p>
        {% endfor %}

    </address>
</div>
{% endblock %}

account_module/templates/account_module/login.html
{% extends 'base.html' %}

{% block body %}


    <section id="form" ><!--form-->

        <div class="row" >

            <div class="col-sm-6 col-md-offset-3">

                <div class="signup-form"><!--sign up form-->

                    <h2>ورود</h2>
                    <form method="post" action="">
                        {% csrf_token %}
                        {{ form.as_p }}
                        <a href="{% url 'register:register_page' %}"><p>ثبت نام نکرده اید؟</p></a>
                        <button type="submit" class="btn btn-default">ورود</button>
                    </form>
                </div><!--/sign up form-->
            </div>
        </div>
    </section>
{% endblock %}

account_module/templates/account_module/register_page.html
{% extends 'base.html' %}
 {% block body %}


        <div class="container">
            <div class="col-sm-4">
                <div class="signup-form"><!--sign up form-->
                    <h2>ثبت نام کاربـر جدیـد</h2>
                    <form method="post" action="">
                        {% csrf_token %}
                        {{ form.as_p }}

                        <a href="{% url 'register:login_page' %}"><p>قبلا ثبت نام کرده اید؟</p></a>

                        <button type="submit" class="btn btn-default">ثبت نام</button>
{#                        <input type="submit" value="ثبت نام" class="btn btn-default color" >#}
                    </form>
                </div><!--/sign up form-->
            </div>
        </div>

 {% endblock %}