Hotel/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home_module.urls',namespace='home')),
    path('register/', include('account_module.urls', namespace='register')),
    path('panel/', include('user_panel_module.urls',namespace='panel')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

home_module/urls.py
from django.urls import path
from . import views

app_name = 'home'
urlpatterns = [
    path('', views.RoomView.as_view(), name='room'),
    path('<int:pk>', views.DetailRoomView.as_view(), name='detail_room'),
    path('reserved/<int:pk>/',views.ReservedView.as_view(),name='reserved')

]

home_module/models.py
from django.db import models

from account_module.models import User


# Create your models here.

class HotelRoom(models.Model):
    title = models.CharField(max_length=200, verbose_name='عنوان')
    bed_room = models.SmallIntegerField(verbose_name='تعداد تخت')
    is_bb = models.BooleanField(default=False, verbose_name='همراه با صبحانه؟')
    price = models.IntegerField(verbose_name='قیمت')

    def __str__(self):
        return str(self.title)

    class Meta:
        verbose_name = 'اتاق'
        verbose_name_plural = 'اتاق ها'


class DetailRoom(models.Model):
    title = models.ForeignKey(HotelRoom, on_delete=models.CASCADE, verbose_name='عنوان')
    description = models.TextField(verbose_name='توضیحات')
    image = models.ImageField(verbose_name='عکس', upload_to='room/', null=True, blank=True)

    Reservation = models.BooleanField(verbose_name='رزرو شده/ نشده', null=True)

    def __str__(self):
        return str(self.title)

    class Meta:
        verbose_name = ' جزییات اتاق'
        verbose_name_plural = 'جزییات اتاق ها'


class Reserved(models.Model):
    room = models.ForeignKey(DetailRoom, related_name='hotel_booking', on_delete=models.CASCADE, verbose_name='اتاق')
    user = models.ForeignKey(User, related_name='user_booking', on_delete=models.CASCADE, verbose_name='شخص')
    date_in = models.DateField(verbose_name='تاریخ ورود', null=True)
    date_out = models.DateField(verbose_name='تاریخ خروج', null=True)

    def __str__(self):
        return str(self.room)

    class Meta:
        verbose_name = 'رزرو'
        verbose_name_plural = 'رزرو شده ها'

home_module/forms.py
from django import forms
from django.forms import HiddenInput


class RoomForm(forms.Form):
    date_in = forms.DateField(
        widget=forms.widgets.DateInput(
            attrs={
                'type': 'date', 'placeholder': 'yyyy-mm-dd (DOB)',
                'class': 'form-control'
                }
            ),
        label='تاریخ ورود',
    )
    date_out = forms.DateField(
        widget=forms.widgets.DateInput(
            attrs={
                'type': 'date', 'placeholder': 'yyyy-mm-dd (DOB)',
                'class': 'form-control'
            }
        ),
        label='تاریخ خروج', )

home_module/views.py
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView
from home_module.models import HotelRoom, DetailRoom, Reserved


class RoomView(ListView):
    template_name = 'home_module/room_page.html'
    model = HotelRoom


class DetailRoomView(DetailView):
    template_name = 'home_module/detail_room.html'
    model = DetailRoom


class ReservedView(CreateView):
    template_name = 'home_module/reserved.html'
    model = Reserved
    fields = ['date_in', 'date_out']
    success_url = reverse_lazy('home:secsos')

    def form_valid(self, form, *args, **kwargs):
        reserved = form.save(commit=False)
        reserved.user = self.request.user
        reserved.room = DetailRoom.objects.get(id=self.kwargs['pk'])
        return super().form_valid(form)

home_module/templates/home_module/detail_room.html
{% extends 'base.html' %}
{% block body %}

<section>
    <div class="container">
        <div class="row">

            <div class="col-sm-9 padding-right">
                <div class="product-details"><!--product-details-->
                    <div class="col-sm-5">
                        <div class="view-product">
                            <img src="{{ object.image.url }}" alt="" width="330" height="300">
                        </div>

                        <div id="similar-product" class="carousel slide" data-ride="carousel">

                            <!-- Wrapper for slides -->

                            <!-- Controls -->
                            <a class="right item-control" href="#similar-product" data-slide="next">
                                <i class="fa fa-angle-right"></i>
                            </a>
                            <a class="left item-control" href="#similar-product" data-slide="prev">
                                <i class="fa fa-angle-left"></i>
                            </a>
                        </div>

                    </div>
                    <div class="col-sm-7">
                        <div class="product-information"><!--/product-information-->
                            <img src="/static/images/product-details/new.png" class="newarrival" alt="">
                            <div>
                                <h2>{{ object.title }}</h2>
                            </div>
                            <div>
									<span>
										<span>{{ object.title.price }} تومان </span>
									</span>




{#                                <form method="post">#}
{#                                    {% csrf_token %}#}
{#                                    <div class="row form-group">#}
{#                                        <div class="col-md-12">#}
{#                                            <label for="mintopay">تاریخ ورود</label>#}
{#                                            <p>#}
{#                                                <input type="date" name="checkin" id="checkin" class="form-control">#}
{#                                            </p>#}
{#                                        </div>#}
{#                                        <div class="col-md-12">#}
{#                                            <label for="maxtopay">تاریخ خروجی</label>#}
{#                                            <p>#}
{#                                                <input type="date" name="checkout" id="checkout" class="form-control">#}
{#                                            </p>#}
{#                                        </div>#}
{#                                    </div>#}

                                    <div class="row form-group">
                                        <form action="{% url 'home:reserved' object.id %}" method="post">
                                            {% csrf_token %}
                                            {% if object.Reservation is False %}
                                                <div class="col-md-12">
                                                    <input type="submit" class="btn btn-primary btn-block" value="رزرو">
                                                </div>
                                            {% else %}
                                                <h4>این اتاق رزرو شده است</h4>
                                            {% endif %}
                                        </form>
                                    </div>

{#                                </form>#}

                                <br>

                                <h4>{{ object.description }}</h4>
                                {% if object.title.is_bb %}
                                    <p>همراه با صبحانه</p>


                                {% endif %}
                                </span>
                            </div>


                        </div><!--/product-information-->


                    </div>
                </div><!--/product-details-->


            </div>


        </div>
    </div>
</section>
{% endblock %}

home_module/templates/home_module/reserved.html
{% extends 'base.html' %}
{% block body %}
    <form action="" method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="رزرو">
    </form>
{% endblock %}

home_module/templates/home_module/room_page.html
{% extends 'base.html' %}
{% block body %}
	<section>
    <div class="container">
        <div class="row">

            <div class="col-sm-9 padding-right">
                <div class="features_items"><!--features_items-->

                    <h2 class="title text-center">اتاق ها</h2>

                    {% for rooms in object_list %}

                        <div class="col-sm-4">
                            <div class="product-image-wrapper">
                                <div class="single-products">

                                    <div class="productinfo text-center">
                                        <img src="images/shop/product.jpg" alt="">
                                        <h2>{{ rooms.price }} تومان</h2>
                                        <p>{{ rooms.title }}</p>

                                        <a href="{% url 'home:detail_room' rooms.id %}" class="btn btn-default add-to-cart"><i
                                                class="fa fa-shopping-cart"></i>
                                            جزییات</a>

                                        {% if rooms.is_bb %}
                                            <p>همراه با صبحانه</p>

                                        {% endif %}


                                    </div>
                                </div>

                            </div>
                        </div>

                    {% endfor %}


                </div>


            </div><!--features_items-->
        </div>


    </div>
    </div>
</section>

{% endblock %}

home_module/templates/home_module/seccsos.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h2>اتاق شما با موفقیت رزرو شد</h2>
<h4><a href="{% url 'home:room' %}">بازگشت به صفحه اصلی</a></h4>
</body>
</html>